# 项目初始化配置
main:
    host: 127.0.0.1
    port: 8080

# mysql配置
mysql:
    username: root
    password: jdtlh
    host: localhost
    port: 3306
    database: test
    suffix: charset=utf8&parseTime=true&loc=Local